### ISSUE TITLE
DMA

### ISSUE THREAD

**Issue by stefanlinden** [DelfiSpace/DWire#1]
For performance optimisation, it is recommended to look into using DMA (Direct Memory Access) as a buffer mechanism instead of a normal statically defined byte array.

**Comment by johcarvajal** [comment]
Do you provide a function for DMA software request? What is the memory space used for this purpose?

**Comment by stefanlinden** [comment]
This is not yet implemented: the buffer is still fully processor-controlled. TI's driverlib includes a simplified API for an I2C/DMA combination, which would increase buffer responsiveness and reduce overall power consumption.

**Comment by stefanlinden** [comment]
Closed as this is now not deemed to be necessary anymore
