### ISSUE TITLE
Possible deadlocks

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DWire#10]
There are several while loops with only one condition to extra the loop (line 136, 191, 221, 246). These can lead to deadlocks in case of errors during I2C transmission and should be removed.

Some timeout mechanism should be set in place to ensure that the system cannot be locked.

**Comment by stefanlinden** [comment]
As far as I know, there are two main methods of tackling this:
1. Use the timer module to activate a watchdog. Programmatically the nicer option, but this could cause problems with multiple running instances and/or take away resources from the main program.
2. Simply add a counter which breaks the loop at a predefined level. This is my preferred option for the moment, but this will require care to make sure everything is cleaned up correctly in the case of a timeout.

**Comment by StefanoSperetta** [comment]
Agree with you on option 2. One drawback could also be the "granularity" in response times that you could get because you add more code inside the while loop. Ideally a nice way would be to call the mills() function so you can set a reasonable timeout but I am not sure if this will slow something down (because mills() takes some time to be executed) and maybe make you loose one transition.

It would be probably worth a try because just counting the number of iterations of the loop depends on the clock speed and at 48MHz we may need to use an int and anyway find a way to relate the count to a time in milliseconds.

**Comment by StefanoSperetta** [comment]
I added one more thread to the sketch that just blinks an LED using delays and this thread also gets stuck. So, in Energia, when 1 thread is stuck, the whole CPU is stuck.

**Comment by stefanlinden** [comment]
All possible deadlocks should now be fixed after analysis with (extreme) interference generated with a signal generation.
