### ISSUE TITLE
Dynamic handling of interrupts

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DWire#11]
The I2C interrupt are handled dynamically creating a C interrupt handler that resolves dynamically which DWire object is linked to the module being used. This makes the structure of the code quite complex and lengthens execution time.

A simpler way could be to make the IRQParam part of the object as a private member (this will eliminate all the replicas, one for each I2C module and reduce the global memory footprint). If the information is private, you can protect it from the rest of the world and ignore scope problems: every class will be aware where its own buffer is... Plus, you will minimise the memory footprint in most cases because only 1 buffer will exist and not 4 (keep in mind that in the way you created it, the global variables will be in RAM because you are assigning multiple times).

Then an array of global pointers to DWire can be used to select which instance to use and map to interrupts. Each time one DWire instance is created, only the corresponding pointer (to I2C module 0, 1, etc) is updated and the others are kept at 0 by default.

An array of static interrupt handlers can be created, each of them with an hardcoded I2C module index and this function will call a generic function (part of the class) in this way:

DWire *table[4];

extern "C" {
void EUSCIB0_IRQHandler(void) {
  table[0]->handleIRQ();
}
}

extern "C" {
void EUSCIB1_IRQHandler(void) {
  table[1]-> handleIRQ();
}
}

You could also remove the code that initialises all the structures in _initMain, and just leave access through the provate members. What will still be needed are the functions that map the specific IRW handlers.

At this point, the interrupt handler is part of the class and you can use it without the ModuleMap (just because, as part of the class, it has access to all the private members, including the buffers and the module address). This way all the information is kept private and you always get access through the pointer to the function and the stub C-to-C++ functions. But those 4 functions are the only part of the code that is repeated so possible errors are minimised. You should check if this allows you to move the stop code in the generic function. Unfortunately there are no optimisations you can do to the array / hash scheme more than this, but you only have 1 address resolution, which should not be so worse than the current version.

**Comment by stefanlinden** [comment]
Fixed but awaiting merge into master
