### ISSUE TITLE
requestFrom locks when requesting from not existing device

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DWire#12]
When executing the following code against a non existing device, the system locks at the requestFrom call.

```
wire.beginTransmission(address);
wire.write(reg);
wire.endTransmission(false);
unsigned char res = wire.requestFrom(address, 2);
```

The code is used to read from a register (reg) on a INA226. The crash happens with single was and multitasking applications.

**Comment by stefanlinden** [comment]
Solved in Issue11, but awaiting merge into master.
