### ISSUE TITLE
Get the DSerial out of DWire

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DWire#14]
The DSerial object should not be in this project... it should go into an independent library...
Maybe create a nice static console object to simplify stuff

**Comment by StefanoSperetta** [comment]
@CasperBroekhuizen: do we still have good reasons to keep DSerial in DWire or can we get rid of it now?

**Comment by CasperBroekhuizen** [comment]
I agree to get rid of it. DSerial has been superseded by the Console, removing it now will avoid someone with limited knowledge of using it.

**Comment by StefanoSperetta** [comment]
Done in https://github.com/DelfiSpace/FlightSoftwareWorkspace/commit/3ea40e0efdeba44cd1d2519ad9219be972151727
