### ISSUE TITLE
Add the possibility to set I2C speed

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/DWire#9]
I2C speed (100 or 400 KHz) is needed to configure the system. It could be added as a parameter to the begin function (both for the transmitter and the receiver) so the user could select the mode.

**Comment by stefanlinden** [comment]
I think to stay with the philosophy of keeping the library's abstraction layer as high as possible, this needs to be made as an optional argument.

**Comment by StefanoSperetta** [comment]
I agree but it may be tricky on the implementation side. There is already 1 optional parameter (address) used to select between master and slave. If we add one more parameter optional we could have 3 possible cases: 1, 2 and 3 parameters (if we move the module to the constructor) but then it would be tricky to decide which parameter is which. 

Maybe it could be easier to add just a separate function to be called before begin that sets the speed.

**Comment by StefanoSperetta** [comment]
Feature added in changeset 27990fc83d7523ce767c2dfa94a29305a665b741. Needs to be properly tested.

**Comment by StefanoSperetta** [comment]
Tested and works like a charm.
